-- ============================================
-- PRODUCTS TABLE UPDATE & SEED
-- ============================================

-- 1. MODIFY TABLE STRUCTURE
-- Ensure products table has images column and no image column
-- (This part assumes the user has already run the migration, but we include schema definition for reference)
-- CREATE TABLE IF NOT EXISTS products (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     title VARCHAR(255) NOT NULL,
--     description TEXT,
--     price DECIMAL(10, 2) NOT NULL,
--     category VARCHAR(255),
--     images JSON, -- New JSON column for multiple images
--     stock INT DEFAULT 0,
--     rating_rate DECIMAL(3, 2) DEFAULT 0,
--     rating_count INT DEFAULT 0,
--     source VARCHAR(50) DEFAULT NULL,
--     external_id INT DEFAULT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );

-- 2. INSERT PRODUCT DATA
INSERT INTO products (title, description, price, category, images, stock, rating_rate, rating_count, source, external_id) VALUES
('Essence Mascara Lash Princess', 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.', 9.99, 'beauty', '["https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp"]', 99, 2.56, 3, 'dummyjson', 1),
('Eyeshadow Palette with Mirror', 'The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it''s convenient for the on-the-go makeup application.', 19.99, 'beauty', '["https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp"]', 34, 2.86, 3, 'dummyjson', 2),
('Powder Canister', 'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.', 14.99, 'beauty', '["https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp"]', 89, 4.64, 3, 'dummyjson', 3),
('Red Lipstick', 'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.', 12.99, 'beauty', '["https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp"]', 91, 4.36, 3, 'dummyjson', 4),
('Red Nail Polish', 'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.', 8.99, 'beauty', '["https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp"]', 79, 4.32, 3, 'dummyjson', 5),
('Calvin Klein CK One', 'CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It''s a versatile fragrance suitable for everyday wear.', 49.99, 'fragrances', '["https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp", "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp", "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp"]', 29, 4.37, 3, 'dummyjson', 6),
('Chanel Coco Noir Eau De', 'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.', 129.99, 'fragrances', '["https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp", "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp", "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp"]', 58, 4.26, 3, 'dummyjson', 7),
('Dior J''adore', 'J''adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.', 89.99, 'fragrances', '["https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/1.webp", "https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/2.webp", "https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/3.webp"]', 98, 3.8, 3, 'dummyjson', 8),
('Dolce Shine Eau de', 'Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It''s a joyful and youthful scent.', 69.99, 'fragrances', '["https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp", "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp", "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp"]', 4, 3.96, 3, 'dummyjson', 9),
('Gucci Bloom Eau de', 'Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It''s a modern and romantic scent.', 79.99, 'fragrances', '["https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp", "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp", "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp"]', 91, 2.74, 3, 'dummyjson', 10),
('Annibale Colombo Bed', 'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.', 1899.99, 'furniture', '["https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp", "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp", "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp"]', 88, 4.77, 3, 'dummyjson', 11),
('Annibale Colombo Sofa', 'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.', 2499.99, 'furniture', '["https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp", "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/2.webp", "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/3.webp"]', 60, 3.92, 3, 'dummyjson', 12),
('Bedside Table African Cherry', 'The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.', 299.99, 'furniture', '["https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/1.webp", "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/2.webp", "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/3.webp"]', 64, 2.87, 3, 'dummyjson', 13),
('Knoll Saarinen Executive Conference Chair', 'The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.', 499.99, 'furniture', '["https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/1.webp", "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/2.webp", "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/3.webp"]', 26, 4.88, 3, 'dummyjson', 14),
('Wooden Bathroom Sink With Mirror', 'The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.', 799.99, 'furniture', '["https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/1.webp", "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/2.webp", "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/3.webp"]', 7, 3.59, 3, 'dummyjson', 15),
('Apple', 'Fresh and crisp apples, perfect for snacking or incorporating into various recipes.', 1.99, 'groceries', '["https://cdn.dummyjson.com/product-images/groceries/apple/1.webp"]', 8, 4.19, 3, 'dummyjson', 16),
('Beef Steak', 'High-quality beef steak, great for grilling or cooking to your preferred level of doneness.', 12.99, 'groceries', '["https://cdn.dummyjson.com/product-images/groceries/beef-steak/1.webp"]', 86, 4.47, 3, 'dummyjson', 17),
('Cat Food', 'Nutritious cat food formulated to meet the dietary needs of your feline friend.', 8.99, 'groceries', '["https://cdn.dummyjson.com/product-images/groceries/cat-food/1.webp"]', 46, 3.13, 3, 'dummyjson', 18),
('Chicken Meat', 'Fresh and tender chicken meat, suitable for various culinary preparations.', 9.99, 'groceries', '["https://cdn.dummyjson.com/product-images/groceries/chicken-meat/1.webp", "https://cdn.dummyjson.com/product-images/groceries/chicken-meat/2.webp"]', 97, 3.19, 3, 'dummyjson', 19),
('Cooking Oil', 'Versatile cooking oil suitable for frying, sautéing, and various culinary applications.', 4.99, 'groceries', '["https://cdn.dummyjson.com/product-images/groceries/cooking-oil/1.webp"]', 10, 4.8, 3, 'dummyjson', 20),
('Cucumber', 'Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.', 1.49, 'groceries', '["https://cdn.dummyjson.com/product-images/groceries/cucumber/1.webp"]', 84, 4.07, 3, 'dummyjson', 21),
('Dog Food', 'Specially formulated dog food designed to provide essential nutrients for your canine companion.', 10.99, 'groceries', '["https://cdn.dummyjson.com/product-images/groceries/dog-food/1.webp"]', 71, 4.55, 3, 'dummyjson', 22),
('Eggs', 'Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.', 2.99, 'groceries', '["https://cdn.dummyjson.com/product-images/groceries/eggs/1.webp"]', 9, 2.53, 3, 'dummyjson', 23),
('Fish Steak', 'Quality fish steak, suitable for grilling, baking, or pan-searing.', 14.99, 'groceries', '["https://cdn.dummyjson.com/product-images/groceries/fish-steak/1.webp"]', 74, 3.78, 3, 'dummyjson', 24),
('Green Bell Pepper', 'Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.', 1.29, 'groceries', '["https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/1.webp"]', 33, 3.25, 3, 'dummyjson', 25),
('Decoration Swing', 'The Decoration Swing is a charming addition to your home decor. Crafted with intricate details, it adds a touch of elegance and whimsy to any room.', 59.99, 'home-decoration', '["https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/1.webp", "https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/2.webp", "https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/3.webp"]', 47, 3.16, 3, 'dummyjson', 43),
('Family Tree Photo Frame', 'The Family Tree Photo Frame is a sentimental and stylish way to display your cherished family memories. With multiple photo slots, it tells the story of your loved ones.', 29.99, 'home-decoration', '["https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/1.webp"]', 77, 4.53, 3, 'dummyjson', 44),
('House Showpiece Plant', 'The House Showpiece Plant is an artificial plant that brings a touch of nature to your home without the need for maintenance. It adds greenery and style to any space.', 39.99, 'home-decoration', '["https://cdn.dummyjson.com/product-images/home-decoration/house-showpiece-plant/1.webp", "https://cdn.dummyjson.com/product-images/home-decoration/house-showpiece-plant/2.webp", "https://cdn.dummyjson.com/product-images/home-decoration/house-showpiece-plant/3.webp"]', 28, 4.67, 3, 'dummyjson', 45),
('Plant Pot', 'The Plant Pot is a stylish container for your favorite plants. With a sleek design, it complements your indoor or outdoor garden, adding a modern touch to your plant display.', 14.99, 'home-decoration', '["https://cdn.dummyjson.com/product-images/home-decoration/plant-pot/1.webp", "https://cdn.dummyjson.com/product-images/home-decoration/plant-pot/2.webp", "https://cdn.dummyjson.com/product-images/home-decoration/plant-pot/3.webp", "https://cdn.dummyjson.com/product-images/home-decoration/plant-pot/4.webp"]', 59, 3.01, 3, 'dummyjson', 46),
('Table Lamp', 'The Table Lamp is a functional and decorative lighting solution for your living space. With a modern design, it provides both ambient and task lighting, enhancing the atmosphere.', 49.99, 'home-decoration', '["https://cdn.dummyjson.com/product-images/home-decoration/table-lamp/1.webp"]', 9, 3.55, 3, 'dummyjson', 47),
('Apple MacBook Pro 14 Inch Space Grey', 'The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple''s M1 Pro chip for exceptional performance and a stunning Retina display.', 1999.99, 'laptops', '["https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/1.webp", "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/2.webp", "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/3.webp"]', 24, 3.65, 3, 'dummyjson', 78),
('Asus Zenbook Pro Dual Screen Laptop', 'The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals.', 1799.99, 'laptops', '["https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/1.webp", "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/2.webp", "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/3.webp"]', 45, 3.95, 3, 'dummyjson', 79),
('Huawei Matebook X Pro', 'The Huawei Matebook X Pro is a slim and stylish laptop with a high-resolution touchscreen display, offering a premium experience for users on the go.', 1399.99, 'laptops', '["https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/1.webp", "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/2.webp", "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/3.webp"]', 75, 4.98, 3, 'dummyjson', 80),
('Lenovo Yoga 920', 'The Lenovo Yoga 920 is a 2-in-1 convertible laptop with a flexible hinge, allowing you to use it as a laptop or tablet, offering versatility and portability.', 1099.99, 'laptops', '["https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/1.webp", "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/2.webp", "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/3.webp"]', 40, 2.86, 3, 'dummyjson', 81),
('New DELL XPS 13 9300 Laptop', 'The New DELL XPS 13 9300 Laptop is a compact and powerful device, featuring a virtually borderless InfinityEdge display and high-end performance for various tasks.', 1499.99, 'laptops', '["https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/1.webp", "https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/2.webp", "https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/3.webp"]', 74, 2.67, 3, 'dummyjson', 82),
('Blue & Black Check Shirt', 'The Blue & Black Check Shirt is a stylish and comfortable men''s shirt featuring a classic check pattern. Made from high-quality fabric, it''s suitable for both casual and semi-formal occasions.', 29.99, 'mens-shirts', '["https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/2.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/3.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/4.webp"]', 38, 3.64, 3, 'dummyjson', 83),
('Gigabyte Aorus Men Tshirt', 'The Gigabyte Aorus Men Tshirt is a cool and casual shirt for gaming enthusiasts. With the Aorus logo and sleek design, it''s perfect for expressing your gaming style.', 24.99, 'mens-shirts', '["https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/2.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/3.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/4.webp"]', 90, 3.18, 3, 'dummyjson', 84),
('Man Plaid Shirt', 'The Man Plaid Shirt is a timeless and versatile men''s shirt with a classic plaid pattern. Its comfortable fit and casual style make it a wardrobe essential for various occasions.', 34.99, 'mens-shirts', '["https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/2.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/3.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/4.webp"]', 82, 3.46, 3, 'dummyjson', 85),
('Man Short Sleeve Shirt', 'The Man Short Sleeve Shirt is a breezy and stylish option for warm days. With a comfortable fit and short sleeves, it''s perfect for a laid-back yet polished look.', 19.99, 'mens-shirts', '["https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/2.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/3.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/4.webp"]', 2, 2.9, 3, 'dummyjson', 86),
('Men Check Shirt', 'The Men Check Shirt is a classic and versatile shirt featuring a stylish check pattern. Suitable for various occasions, it adds a smart and polished touch to your wardrobe.', 27.99, 'mens-shirts', '["https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/2.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/3.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/4.webp"]', 95, 2.72, 3, 'dummyjson', 87);
